### ISSUE TITLE
Update version gem "excon", to version .20 as needed by engine 2.1

### ISSUE THREAD

**Issue by nonfungibletunji** [locomotivecms/locomotive-heroku#5]
Trying to upgrade loco 2.1, i get the following error.

Bundler could not find compatible versions for gem "excon":
  In Gemfile:
    locomotive-heroku (~> 0.0.2) ruby depends on
      excon (~> 0.9.4) ruby

```
locomotive_cms (>= 0) ruby depends on
  excon (0.20.0)
```

**Comment by benjaminwood** [comment]
Same issue here, I don't think its just us! I wonder if it is possible to upgrade to engine 2.1 while using locomotive-heroku?

Locomotive-heroku is dependent on heroku-api v 0.1.0 which is dependent on excon v 0.9.4 which is not compatible with engine required excon v 0.20.0.

http://rubygems.org/gems/heroku-api/versions/0.1.0

**Comment by asecondwill** [comment]
So we need 
locomotive to bump dependency for excon to 0.23.0
locomotive-heroku to bump to heroku.rb 0.3.12  (which uses 0.23.0)

... i think.  Needs someone much more knowledgeable than me to fix this.

**Comment by did** [comment]
Fixed here: https://github.com/locomotivecms/locomotive-heroku/pull/6
I merged it + make all the tests pass. A new gem coming soon !

**Comment by benjaminwood** [comment]
Great, thanks Didier!

**Comment by did** [comment]
the 0.1.0 gem is out. could you try it and let me know if it works great. thanks !

**Comment by benjaminwood** [comment]
Done. www.crossroadschurch.net running on heroku with engine 2.1.4 and locomotive-heroku 0.1.0. Everything seems to be working as expected. Thanks again @did  and @asecondwill.

Note to those that might read this:
Be sure to update your config/mongoid.yml to the new spec. You'll need something along the lines of:

```
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
```

**Comment by did** [comment]
You're welcome ! Nice website btw !!!

**Comment by benjaminwood** [comment]
Thanks! We love locomotive, thanks for all your hard work.
