### ISSUE TITLE
Failed AWS authorization

### ISSUE THREAD

**Issue by olhapi** [locomotivecms/locomotive-heroku#9]
- Pushing Pages
  en
    updating index{"error"=>"Expected(200) <=> Actual(400 Bad Request)\n  response => #<Excon::Response:0x007f86ed863be0 @data={:body=>\"<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>5F63FD1C5AFFD77C</RequestId><HostId>FGZI3zQq9oHxeoEfEXxWWsq4sHiqJ99ew5G62vSyuxafgmqpuVlEY04t7JpcTFkMUt6v03fqqZE=</HostId></Error>\", :headers=>{\"x-amz-request-id\"=>\"5F63FD1C5AFFD77C\", \"x-amz-id-2\"=>\"FGZI3zQq9oHxeoEfEXxWWsq4sHiqJ99ew5G62vSyuxafgmqpuVlEY04t7JpcTFkMUt6v03fqqZE=\", \"Content-Type\"=>\"application/xml\", \"Transfer-Encoding\"=>\"chunked\", \"Date\"=>\"Sat, 24 Jan 2015 16:58:04 GMT\", \"Connection\"=>\"close\", \"Server\"=>\"AmazonS3\"}, :status=>400, :remote_ip=>\"54.231.193.1\"}, @body=\"<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>5F63FD1C5AFFD77C</RequestId><HostId>FGZI3zQq9oHxeoEfEXxWWsq4sHiqJ99ew5G62vSyuxafgmqpuVlEY04t7JpcTFkMUt6v03fqqZE=</HostId></Error>\", @headers={\"x-amz-request-id\"=>\"5F63FD1C5AFFD77C\", \"x-amz-id-2\"=>\"FGZI3zQq9oHxeoEfEXxWWsq4sHiqJ99ew5G62vSyuxafgmqpuVlEY04t7JpcTFkMUt6v03fqqZE=\", \"Content-Type\"=>\"application/xml\", \"Transfer-Encoding\"=>\"chunked\", \"Date\"=>\"Sat, 24 Jan 2015 16:58:04 GMT\", \"Connection\"=>\"close\", \"Server\"=>\"AmazonS3\"}, @status=400, @remote_ip=\"54.231.193.1\">"}

**Comment by muxamilian** [comment]
Same issue here. Found any solution?

**Comment by olhapi** [comment]
Yep. Switched to Node.js stack.
